
#pragma once


enum DataSourceType
{
	DATA_SOURCE_FILE,
	DATA_SOURCE_DEVICE,
	DATA_SOURCE_COUNT
};

enum ID_PROPERTY_DATA
{
	ID_PROPERTY_INDEX_VALUE,//	0
	ID_PROPERTY_INDEX_TYPE,	//	1
	ID_PROPERTY_SAMPLES,	//	2
	ID_PROPERTY_BANDS,		//	3
	ID_PROPERTY_LINES,		//	4
	ID_PROPERTY_EXPOSURE,	//	5
	ID_PROPERTY_FPS,		//	6
	ID_PROPERTY_RESOLUTION,	//	7
	ID_PROPERTY_REPEAT_B,	//	8
	ID_PROPERTY_REPEAT_N,	//	9
	ID_PROPERTY_COUNT		//	10
};

enum LOG_TYPE
{
	LOG_TYPE_UI		= 1,	// 001
	LOG_TYPE_FILE	= 2,	// 010
	LOG_TYPE_COM	= 4		// 100
};


enum SBG_LOG_TYPE
{
	SBG_LOG_TYPE_ANGLE = 1,	// 001
	SBG_LOG_TYPE_GPS = 2	// 010
};